databases:
  - name: copore_DB
    databaseName: copore_db
    user: copore
    region: singapore

services:
  - type: web
    name: copore
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: copore_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

